### PR TITLE
Fixed "ValueError: unknown locale: UTF-8"

### PR DESCRIPTION
**Pull request by mozillazg**
On Mac OS X may raise this error when preview rst file.

### CODE REVIEW

**Comment by kannokanno** [comment]
thx.
Let me confirm.

**Comment by kannokanno** [comment]
Hmm.
Get error via vimproc.(use 78cbb5c)

```
Error detected while processing function previm#refresh..previm#refresh_js..<SNR>149_function_template..previm#convert_to_content..<SNR>149_do_external_parse..<SNR>149_system..
vimproc#system..<SNR>152_system..vimproc#pgroup_open..<SNR>152_pgroup_open..vimproc#plineopen3..<SNR>152_plineopen..<SNR>152_convert_args..vimproc#get_command_name:
line   15:
E605: Exception not caught: vimproc#get_command_name: File "LC_ALL=en_US.UTF-8" is not found.
Error detected while processing function previm#refresh..previm#refresh_js..<SNR>149_function_template..previm#convert_to_content:
line    7:
E170: Missing :endfor
```

Also, it is this can be run on Windows?
(regardless of the vimproc)

**Comment by mozillazg** [comment]
Sorry, this can't work on Windows.

**Comment by mattn** [comment]
Sorry, this doesn't work on Windows. And I think this is not a problem of previm. So you've better to make command wrapper. Or add option to specify the command.

**Pull request closed without merging**
