### PR TITLE
Update javascript libraries.

### PR DESCRIPTION
**Pull request by beckorz**
Updated javascript libraries.

|Libraries|Version(Current)|Version(New)|
|---|---|---|
|[asciidoctor.js](https://asciidoctor.org/docs/asciidoctor.js/)|1.5.9 |2.2.3|
|[highlight.js](https://highlightjs.org/download/)|9.15.6|10.7.2|
|[markdown-it](https://github.com/markdown-it/markdown-it)|8.4.2|12.0.6|
|[markdown-it-abbr](https://github.com/markdown-it/markdown-it-abbr)|1.0.4||
|[markdown-it-checkbox](https://github.com/mcecot/markdown-it-checkbox)|1.0.0|1.1.1|
|[markdown-it-cjk-breaks](https://github.com/markdown-it/markdown-it-cjk-breaks/)|1.1.3||
|[markdown-it-deflist](https://github.com/markdown-it/markdown-it-deflist)|2.0.3|2.1.0|
|[markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote)|3.0.1|3.0.2|
|[markdown-it-sub](https://github.com/markdown-it/markdown-it-sub)|1.0.0||
|[markdown-it-sup](https://github.com/markdown-it/markdown-it-sup)|1.0.0||
|[textile.js](https://github.com/borgar/textile-js)|2.0.4||
|[mermaid.js](https://github.com/knsv/mermaid)|8.0.0|8.9.2|

### CODE REVIEW

**Comment by ikaros** [comment]
:+1:  Waiting for this too :sweat_smile:

**Comment by mattn** [comment]
Could you please add instruction command for this?

**Comment by mattn** [comment]
Currently, I'm trying to implement load extra libraries.  #170

**Comment by mattn** [comment]
Thank you

**Pull request closed without merging**
