### PR TITLE
support KaTeX code block

### PR DESCRIPTION
**Pull request by sakkke**
````markdown
# gravida cum sociis natoque penatibus

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vivamus arcu felis bibendum ut tristique. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Aenean pharetra magna ac placerat vestibulum lectus. Et malesuada fames ac turpis egestas sed tempus urna.

```katex
a_n = a + (n - 1) \cdot d
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit. Curabitur vitae nunc sed velit dignissim sodales. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Eget dolor morbi non arcu risus quis varius.

````

image

### CODE REVIEW

**Comment by sakkke** [comment]
```markdown
# Hello

text <span class="inlkatex">42{\pi}</span> text

```

image

**Comment by mattn** [comment]
Currently, I'm trying to implement load extra libraries.  #170
Can this PR be applied that way if https://github.com/previm/previm/pull/170 will be merged?

**Comment by mattn** [comment]
Example to add polyjs

https://github.com/previm/previm/pull/162#issuecomment-1154972196

**Comment by mattn** [comment]
```
let g:previm_extra_libraries = [
\  {
\    'name': 'katex',
\    'files': [
\      {
\        'type': 'css',
\        'path': '_/js/extra/texmath.min.css',
\        'url': 'https://cdn.jsdelivr.net/npm/markdown-it-texmath/css/texmath.min.css',
\      },
\      {
\        'type': 'css',
\        'path': '_/css/extra/katex.min.css',
\        'url': 'https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css',
\        'code': [
\          'renderMathInElement(document.body)',
\        ],
\      },
\      {
\        'type': 'js',
\        'path': '_/js/extra/katex-auto-render.min.js',
\        'url': 'https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js',
\        'code': [
\          'renderMathInElement(document.body)',
\        ],
\      },
\      {
\        'type': 'js',
\        'path': '_/js/extra/katex.min.js',
\        'url': 'https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js',
\        'code': [
\          'document.querySelectorAll(''pre code.language-katex'').forEach(elem => {',
\          '  const html = katex.renderToString(elem.innerText, {',
\          '    displayMode: true,',
\          '    output: ''html'',',
\          '    throwOnError: false,',
\          '  })',
\          '  const span = document.createElement(''span'')',
\          '  span.innerHTML = html',
\          '  elem.parentNode.replaceWith(span)',
\          '})',
\          'document.querySelectorAll(''.inlkatex'').forEach(elem => {',
\          '  const html = katex.renderToString(elem.innerText, {',
\          '    output: ''html'',',
\          '    throwOnError: false,',
\          '  })',
\          '  const span = document.createElement(''span'')',
\          '  span.innerHTML = html',
\          '  elem.replaceWith(span)',
\          '})',
\        ],
\      },
\    ],
\  },
\]
```
add this into your vimrc and do `:PrevimUpdateAssets`. Thanks.

**Pull request closed without merging**
